#!/bin/sh

#compile
g++ -std=c++0x main.cpp

#run code
./a.out

#overwrite some files
cp -i 0/qo.orig 0/qo 

cp -i 0/qw.orig 0/qw 

# blockMesh
blockMesh

#setFields
setFields

IMPESFoam

#View mesh
paraFoam
